export enum OrderStatusEnum {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
  PAYMENYT_REFUNDED = 'PAYMENYT_REFUNDED',
  PAYMENYT_CONFIRMED = 'PAYMENYT_CONFIRMED',
  POSTAL_FAILED = 'POSTAL_FAILED',
  FAILED = 'FAILED'
}
